### ISSUE TITLE
Could we not use the package's inline styling, please?

### ISSUE THREAD

**Issue by andrewsantarin** [artisin/semantic-ui-redux-form-fields#13]
Hi, @artisin. I've tried `semantic-ui-redux-form-fields` and so far, and it has been a great little utility belt, but I have difficulties working with the inline styling. 

In some cases, I do not want `formFieldStyles` and the inline styling from `ErrorMsg` to take effect. I'd rather have those inline styles kept as a custom CSS somewhere in this repo, and then we decide whether we want to use it or not.

I could say creating an overriding CSS will help work, but I'm afraid I'll override other CSS classes, too, which means I'll be fighting the inline CSS all the time. Or I could try to do something like removing the inline style as soon as the component mounts:

**Input.jsx**
```javascript
import React, { Component } from 'react';
import { Input as InputComponent } from 'semantic-ui-react';
import { fieldEnhance } from 'semantic-ui-redux-form-fields';

export class Input extends Component {
  componentDidMount() {
    /**
     * @HACK: I had to! The parent <div /> element can't be accessed by other means!
     */
    document.getElementById(this.props.input.name)
      .closest('.Semantic-redux-form-field')
      .removeAttribute("style");
  }

  render() {
    const {
      input: {
        onDragStart,
        onDrop,
        ...input
      },

      ...props
    } = this.props;

    return (
      <InputComponent
        {...input}
        {...props}
        /**
         * NOTE: What if I don't want to have an `id` for this element?
         */
        id={input.name}
      />
    );
  }
}

// Decorate <Input /> with semantic-ui-redux-form-fields's fieldEnhance(ComposedComponent).
export default fieldEnhance(Input);
```

But really, why would I want to do that?

**Comment by fetchTe** [comment]
I see what you're saying and I agree there should be some sort of conditional logic to override/omit the applied styling. I'm ultra busy at the moment, so I probably can't get around to this for another week or so. But I encourage you to give it a shot if you want. All you need to do is apply said `style` conditional logic to https://github.com/artisin/semantic-ui-redux-form-fields/blob/master/lib/index.js#L102 which in turn is consumed by the `fieldEnhance` an HOC enhancer that is applied to all the components.
