### ISSUE TITLE
width prop is lost

### ISSUE THREAD

**Issue by wichert** [artisin/semantic-ui-redux-form-fields#14]
I am trying to create a form with a bit of simple layout, like this:

```html
<Form.Group>
  <Field
    component={Dropdown}
    name="location"
    topLabel="Location"
    options={LOCATION_OPTIONS}
    width={6}
  />
  <Field
    component={Dropdown}
    name="status"
    topLabel="Status"
    options={STATUS_OPTIONS}
    width={6}
  />
</Form.Group>
```

When looking at the rendered DOM the width information gets lost. The React devtools show that `width` is passed to `fieldEnhance(DropdownPure)`, but that does not pass it on to the `Form.Field`

**Comment by fetchTe** [comment]
Sorry, for some reason I was unsubscribed to this project and didn't see this issue. Do you still need help with this?

**Comment by wichert** [comment]
I ended up not using semantic-ui-redux-form-fields, so I don't need help with this myself.
