### ISSUE TITLE
Warning: Failed prop type: Invalid prop `label` of type `object` supplied to `fieldEnhance(pure(InputPure)`, expected `string`.

### ISSUE THREAD

**Issue by discomarra** [artisin/semantic-ui-redux-form-fields#9]
**Environment:** 
react 15.6.2
redux 3.7.2
semantic-ui-react 0.74.2
semantic-ui-redux-form-fields 1.0.0
redux-form 7.1.0

**Expected behavior**
No warnings and the input renders like here https://react.semantic-ui.com/elements/input#input-example-right-labeled-basic

**Actual behavior**
I get the correctly rendered component but with the following warning:
> Warning: Failed prop type: Invalid prop `label` of type `object` supplied to `fieldEnhance(pure(InputPure)`, expected `string`.
    in fieldEnhance(pure(InputPure) (created by Input)
    in Input (created by ConnectedField)
    in ConnectedField (created by Connect(ConnectedField))
    in Connect(ConnectedField) (created by Field)
    in Field (at EquipmentFormPart.jsx:35)
    in div (at EquipmentFormPart.jsx:34)
    in div (at EquipmentFormPart.jsx:33)
    in div (at EquipmentFormPart.jsx:32)
    in div (at EquipmentFormPart.jsx:14)
    in div (at EquipmentFormPart.jsx:13)
    in div (at EquipmentFormPart.jsx:11)
    in EquipmentFormPart (created by Connect(EquipmentFormPart))
    in Connect(EquipmentFormPart) (at NewBuyOrderForm.jsx:24)
    in div (at NewBuyOrderForm.jsx:21)
    in div (at NewBuyOrderForm.jsx:20)
    in div (at NewBuyOrderForm.jsx:16)
    in form (at NewBuyOrderForm.jsx:15)
    in NewBuyOrderForm (created by Form(NewBuyOrderForm))
    in Form(NewBuyOrderForm) (created by Connect(Form(NewBuyOrderForm)))
    in Connect(Form(NewBuyOrderForm)) (created by ReduxForm)
    in ReduxForm (at NewBuyOrderFormContainer.jsx:22)
    in div (at NewBuyOrderFormContainer.jsx:21)
    in NewBuyOrderFormContainer (created by Connect(NewBuyOrderFormContainer))
    in Connect(NewBuyOrderFormContainer) (at Wizard.jsx:21)
    in div (at Tabs.jsx:62)
    in div (at Tabs.jsx:49)
    in Tabs (at Wizard.jsx:9)
    in Unknown (at NewBuyOrderView.jsx:30)
    in div (at HeaderPanel.jsx:6)
    in Unknown (at NewBuyOrderView.jsx:29)
    in div (at NewBuyOrderView.jsx:14)
    in NewBuyOrderView (created by Connect(NewBuyOrderView))
    in Connect(NewBuyOrderView) (at WorkView.jsx:33)
    in div (at WorkView.jsx:29)
    in div (at WorkView.jsx:21)
    in WorkView (created by Connect(WorkView))
    in Connect(WorkView) (at PrivateRoute.jsx:10)
    in Route (at PrivateRoute.jsx:6)
    in PrivateRoute (created by Connect(PrivateRoute))
    in Connect(PrivateRoute) (created by Route)
    in Route (created by withRouter(Connect(PrivateRoute)))
    in withRouter(Connect(PrivateRoute)) (at HomeView.jsx:28)
    in Switch (at HomeView.jsx:21)
    in div (at HomeView.jsx:19)
    in HomeView (created by Connect(HomeView))
    in Connect(HomeView) (at PrivateRoute.jsx:10)
    in Route (at PrivateRoute.jsx:6)
    in PrivateRoute (created by Connect(PrivateRoute))
    in Connect(PrivateRoute) (created by Route)
    in Route (created by withRouter(Connect(PrivateRoute)))
    in withRouter(Connect(PrivateRoute)) (at App.jsx:19)
    in Switch (at App.jsx:17)
    in div (at App.jsx:16)
    in App (created by Connect(App))
    in Connect(App) (created by Route)
    in Route (created by withRouter(Connect(App)))
    in withRouter(Connect(App)) (at index.js:14)
    in div (at index.js:13)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (at index.js:12)
    in Provider (at index.js:11)

**Steps**
The component is used like this:
`<Field
	component={Input}
	name="equipment[temperature]"
	label={{ basic: true, content: 'F' }}
	labelPosition="right"
	placeholder="25&deg;"
	type="number"
	className="order-form-group__text-input"
	disabled={!selectedEquipment || !selectedEquipment.hasRefrigerator}
/>`

**Comment by fetchTe** [comment]
Thanks for the heads up. I just fixed the issue in pr #11 and published the changes `1.0.1`. Update your project and if the problem persists give me a shout.
